# Generated by Django 4.2.30 on 2026-04-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_artist_event_ticketcategory_eventartist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
    ]
